name: csci347
channels:
  - conda-forge
dependencies:
  - appnope=0.1.2=py38h10201cd_2
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hea4295b_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - brotli=1.0.9=h3422bc3_6
  - brotli-bin=1.0.9=h3422bc3_6
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py38h10201cd_1
  - cffi=1.15.0=py38hc67bbb8_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py38h6f2b01f_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - executing=0.8.3=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.29.1=py38hea4295b_0
  - freetype=2.10.4=h17b34a0_1
  - giflib=5.2.1=h27ca646_2
  - importlib-metadata=4.11.2=py38h10201cd_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.9.1=py38h2cb4d76_0
  - ipython=8.1.1=py38h10201cd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.1=py38h10201cd_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h3422bc3_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h10201cd_7
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py38h10201cd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py38h1670459_1
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libbrotlicommon=1.0.9=h3422bc3_6
  - libbrotlidec=1.0.9=h3422bc3_6
  - libbrotlienc=1.0.9=h3422bc3_6
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcxx=12.0.1=h168391b_1
  - libdeflate=1.10=h3422bc3_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=13_osxarm64_openblas
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.3.0=h77dc3b6_3
  - libwebp=1.2.2=h0d20362_0
  - libwebp-base=1.2.2=h3422bc3_1
  - libxcb=1.13=h9b22ae9_1004
  - libzlib=1.2.11=hee7b306_1013
  - llvm-openmp=13.0.1=h455960f_1
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.1.0=py38h33210d7_1
  - matplotlib=3.5.1=py38h150bfb4_0
  - matplotlib-base=3.5.1=py38hb140015_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38hea4295b_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.5.12=pyhd8ed1ab_0
  - nbconvert=6.4.2=py38h10201cd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=hc470f4d_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.7.1=pyhd8ed1ab_0
  - notebook=6.4.8=pyha770c72_0
  - numpy=1.22.3=py38hf29d37f_0
  - openjpeg=2.4.0=h062765e_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=3.0.0=h3422bc3_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py38h3777fb4_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py38h7ff1586_2
  - pip=22.0.4=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - prompt_toolkit=3.0.27=hd8ed1ab_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38hea4295b_0
  - python=3.8.12=hd949e87_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38h51b17a6_1
  - readline=8.1=hedafd6a_0
  - scikit-learn=1.0.2=py38h2cd4032_0
  - scipy=1.8.0=py38hd0c9ec0_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.9.3=py38h10201cd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h72a2b83_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - terminado=0.13.3=py38h10201cd_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=he1e0b03_0
  - tornado=6.1=py38hea4295b_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - unicodedata2=14.0.0=py38hea4295b_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py38h10201cd_1
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.5=h642e427_1
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=hee7b306_1013
  - zstd=1.5.2=h861e0a7_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/csci347
